# Generated by Django 5.1.3 on 2025-01-16 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
    model_name='attendance',
    name='subject',
    field=models.ForeignKey(
        to='attendance.Subject',
        on_delete=models.CASCADE,
        related_name='attendance_records',
        null=True,  # Temporarily allow nulls
    ),
),

        
    migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(related_name='students', to='attendance.subject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(related_name='teachers', to='attendance.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'subject', 'date')},
        ),
    ]
